version: '2'
services:
  web:
    image: nginx:1.14-alpine
    expose:
      - "80"
    ports: 
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - exo
  exo:
    image: exoplatform/exo-community
    environment:
      EXO_PROXY_VHOST: localhost
      EXO_PROXY_PORT: 80
      EXO_DB_HOST: mysql
      EXO_PROXY_SSL: "false"
      EXO_DB_TYPE: mysql
      EXO_DB_NAME: exo
      EXO_DB_USER: exo
      EXO_DB_PASSWORD: my-secret-pw
      EXO_MONGO_HOST: mongo
      EXO_ADDONS_LIST: exo-chat:$${CHAT_VERSION}
      EXO_JVM_LOG_GC_ENABLED: "true"
    volumes:
      - exo_data:/srv/exo
      - exo_logs:/var/log/exo
    depends_on:
      - mysql
      - mongo
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my-super-secret-pw
      MYSQL_DATABASE: exo
      MYSQL_USER: exo
      MYSQL_PASSWORD: my-secret-pw
    volumes:
      - mysql_data:/var/lib/mysql
  mongo:
    image: mongo:4.0
    volumes:
      - mongo_data:/data/db:rw
volumes:
  exo_data:
  exo_logs:
  mysql_data:
  mongo_data:
